[package]
name = "todotui"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12"
chrono = "0.4"
serde = {version = "1.0", features = ["std","rc"]}
postcard = { version = "1.0", features = ["use-std"] }
tuirealm = "1.9"
tui-realm-stdlib = "1.3"
termusic = "0.3.12"

[workspace]
