name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.87.0
        components: rustfmt
    - name: Check Style
      run: cargo fmt --check
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test 